//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicLyric.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool showNicknameSetting {
            get {
                return ((bool)(this["showNicknameSetting"]));
            }
            set {
                this["showNicknameSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool drawBigCircleSetting {
            get {
                return ((bool)(this["drawBigCircleSetting"]));
            }
            set {
                this["drawBigCircleSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool drawMiddleCircleSetting {
            get {
                return ((bool)(this["drawMiddleCircleSetting"]));
            }
            set {
                this["drawMiddleCircleSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool drawSmallerCircleSetting {
            get {
                return ((bool)(this["drawSmallerCircleSetting"]));
            }
            set {
                this["drawSmallerCircleSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool drawBigSquareSetting {
            get {
                return ((bool)(this["drawBigSquareSetting"]));
            }
            set {
                this["drawBigSquareSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool drawMiddleSquareSetting {
            get {
                return ((bool)(this["drawMiddleSquareSetting"]));
            }
            set {
                this["drawMiddleSquareSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool drawSmallerSquareSetting {
            get {
                return ((bool)(this["drawSmallerSquareSetting"]));
            }
            set {
                this["drawSmallerSquareSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool greenAvalonSetting {
            get {
                return ((bool)(this["greenAvalonSetting"]));
            }
            set {
                this["greenAvalonSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool purpleAvalonSetting {
            get {
                return ((bool)(this["purpleAvalonSetting"]));
            }
            set {
                this["purpleAvalonSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool legendaryAvalonSetting {
            get {
                return ((bool)(this["legendaryAvalonSetting"]));
            }
            set {
                this["legendaryAvalonSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool blueAvalonSetting {
            get {
                return ((bool)(this["blueAvalonSetting"]));
            }
            set {
                this["blueAvalonSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool harvestingT1Setting {
            get {
                return ((bool)(this["harvestingT1Setting"]));
            }
            set {
                this["harvestingT1Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool harvestingT2Setting {
            get {
                return ((bool)(this["harvestingT2Setting"]));
            }
            set {
                this["harvestingT2Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool harvestingT3Setting {
            get {
                return ((bool)(this["harvestingT3Setting"]));
            }
            set {
                this["harvestingT3Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool harvestingT4Setting {
            get {
                return ((bool)(this["harvestingT4Setting"]));
            }
            set {
                this["harvestingT4Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool harvestingT5Setting {
            get {
                return ((bool)(this["harvestingT5Setting"]));
            }
            set {
                this["harvestingT5Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool harvestingT6Setting {
            get {
                return ((bool)(this["harvestingT6Setting"]));
            }
            set {
                this["harvestingT6Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool harvestingT7Setting {
            get {
                return ((bool)(this["harvestingT7Setting"]));
            }
            set {
                this["harvestingT7Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool harvestingT8Setting {
            get {
                return ((bool)(this["harvestingT8Setting"]));
            }
            set {
                this["harvestingT8Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool harvestingE1Setting {
            get {
                return ((bool)(this["harvestingE1Setting"]));
            }
            set {
                this["harvestingE1Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool harvestingE2Setting {
            get {
                return ((bool)(this["harvestingE2Setting"]));
            }
            set {
                this["harvestingE2Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool harvestingE3Setting {
            get {
                return ((bool)(this["harvestingE3Setting"]));
            }
            set {
                this["harvestingE3Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool harvestingFiberSetting {
            get {
                return ((bool)(this["harvestingFiberSetting"]));
            }
            set {
                this["harvestingFiberSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool harvestingWoodSetting {
            get {
                return ((bool)(this["harvestingWoodSetting"]));
            }
            set {
                this["harvestingWoodSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool harvestingOreSetting {
            get {
                return ((bool)(this["harvestingOreSetting"]));
            }
            set {
                this["harvestingOreSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool harvestingRockSetting {
            get {
                return ((bool)(this["harvestingRockSetting"]));
            }
            set {
                this["harvestingRockSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool harvestingSizeSetting {
            get {
                return ((bool)(this["harvestingSizeSetting"]));
            }
            set {
                this["harvestingSizeSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool harvestingE0Setting {
            get {
                return ((bool)(this["harvestingE0Setting"]));
            }
            set {
                this["harvestingE0Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int translationWindowXSetting {
            get {
                return ((int)(this["translationWindowXSetting"]));
            }
            set {
                this["translationWindowXSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int translationWindowYSetting {
            get {
                return ((int)(this["translationWindowYSetting"]));
            }
            set {
                this["translationWindowYSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mobE0Setting {
            get {
                return ((bool)(this["mobE0Setting"]));
            }
            set {
                this["mobE0Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mobE1Setting {
            get {
                return ((bool)(this["mobE1Setting"]));
            }
            set {
                this["mobE1Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mobE2Setting {
            get {
                return ((bool)(this["mobE2Setting"]));
            }
            set {
                this["mobE2Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mobE3Setting {
            get {
                return ((bool)(this["mobE3Setting"]));
            }
            set {
                this["mobE3Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mobE4Setting {
            get {
                return ((bool)(this["mobE4Setting"]));
            }
            set {
                this["mobE4Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool showPlayerHealthSetting {
            get {
                return ((bool)(this["showPlayerHealthSetting"]));
            }
            set {
                this["showPlayerHealthSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool showPlayerItemsSetting {
            get {
                return ((bool)(this["showPlayerItemsSetting"]));
            }
            set {
                this["showPlayerItemsSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool soundOnNewPlayerSetting {
            get {
                return ((bool)(this["soundOnNewPlayerSetting"]));
            }
            set {
                this["soundOnNewPlayerSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mountedSetting {
            get {
                return ((bool)(this["mountedSetting"]));
            }
            set {
                this["mountedSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int translationItemsXSetting {
            get {
                return ((int)(this["translationItemsXSetting"]));
            }
            set {
                this["translationItemsXSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int translationItemsYSetting {
            get {
                return ((int)(this["translationItemsYSetting"]));
            }
            set {
                this["translationItemsYSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int itemsOpacitySetting {
            get {
                return ((int)(this["itemsOpacitySetting"]));
            }
            set {
                this["itemsOpacitySetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool showPlayerDistanceSetting {
            get {
                return ((bool)(this["showPlayerDistanceSetting"]));
            }
            set {
                this["showPlayerDistanceSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool dungeonE0BindSetting {
            get {
                return ((bool)(this["dungeonE0BindSetting"]));
            }
            set {
                this["dungeonE0BindSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool dungeonE1BindSetting {
            get {
                return ((bool)(this["dungeonE1BindSetting"]));
            }
            set {
                this["dungeonE1BindSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool dungeonE2BindSetting {
            get {
                return ((bool)(this["dungeonE2BindSetting"]));
            }
            set {
                this["dungeonE2BindSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool dungeonE3BindSetting {
            get {
                return ((bool)(this["dungeonE3BindSetting"]));
            }
            set {
                this["dungeonE3BindSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool dungeonE4BindSetting {
            get {
                return ((bool)(this["dungeonE4BindSetting"]));
            }
            set {
                this["dungeonE4BindSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mistE0BindSetting {
            get {
                return ((bool)(this["mistE0BindSetting"]));
            }
            set {
                this["mistE0BindSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mistE1BindSetting {
            get {
                return ((bool)(this["mistE1BindSetting"]));
            }
            set {
                this["mistE1BindSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mistE2BindSetting {
            get {
                return ((bool)(this["mistE2BindSetting"]));
            }
            set {
                this["mistE2BindSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mistE3BindSetting {
            get {
                return ((bool)(this["mistE3BindSetting"]));
            }
            set {
                this["mistE3BindSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mistE4BindSetting {
            get {
                return ((bool)(this["mistE4BindSetting"]));
            }
            set {
                this["mistE4BindSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mistSoloSetting {
            get {
                return ((bool)(this["mistSoloSetting"]));
            }
            set {
                this["mistSoloSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mistDuoSetting {
            get {
                return ((bool)(this["mistDuoSetting"]));
            }
            set {
                this["mistDuoSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool dungeonSoloSetting {
            get {
                return ((bool)(this["dungeonSoloSetting"]));
            }
            set {
                this["dungeonSoloSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool dungeonDuoSetting {
            get {
                return ((bool)(this["dungeonDuoSetting"]));
            }
            set {
                this["dungeonDuoSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool corruptSetting {
            get {
                return ((bool)(this["corruptSetting"]));
            }
            set {
                this["corruptSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hellgateSetting {
            get {
                return ((bool)(this["hellgateSetting"]));
            }
            set {
                this["hellgateSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int sizeHarvestingSetting {
            get {
                return ((int)(this["sizeHarvestingSetting"]));
            }
            set {
                this["sizeHarvestingSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int itemsSizeSetting {
            get {
                return ((int)(this["itemsSizeSetting"]));
            }
            set {
                this["itemsSizeSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool radarColorsSetting {
            get {
                return ((bool)(this["radarColorsSetting"]));
            }
            set {
                this["radarColorsSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool spiderSetting {
            get {
                return ((bool)(this["spiderSetting"]));
            }
            set {
                this["spiderSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool weilWeaverSetting {
            get {
                return ((bool)(this["weilWeaverSetting"]));
            }
            set {
                this["weilWeaverSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool fairyDragonSetting {
            get {
                return ((bool)(this["fairyDragonSetting"]));
            }
            set {
                this["fairyDragonSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool griffinSetting {
            get {
                return ((bool)(this["griffinSetting"]));
            }
            set {
                this["griffinSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mobT1Setting {
            get {
                return ((bool)(this["mobT1Setting"]));
            }
            set {
                this["mobT1Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mobT2Setting {
            get {
                return ((bool)(this["mobT2Setting"]));
            }
            set {
                this["mobT2Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mobT3Setting {
            get {
                return ((bool)(this["mobT3Setting"]));
            }
            set {
                this["mobT3Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mobT4Setting {
            get {
                return ((bool)(this["mobT4Setting"]));
            }
            set {
                this["mobT4Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mobT5Setting {
            get {
                return ((bool)(this["mobT5Setting"]));
            }
            set {
                this["mobT5Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mobT6Setting {
            get {
                return ((bool)(this["mobT6Setting"]));
            }
            set {
                this["mobT6Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mobT7Setting {
            get {
                return ((bool)(this["mobT7Setting"]));
            }
            set {
                this["mobT7Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mobT8Setting {
            get {
                return ((bool)(this["mobT8Setting"]));
            }
            set {
                this["mobT8Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mobHarvestableSetting {
            get {
                return ((bool)(this["mobHarvestableSetting"]));
            }
            set {
                this["mobHarvestableSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mobSkinnableSetting {
            get {
                return ((bool)(this["mobSkinnableSetting"]));
            }
            set {
                this["mobSkinnableSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mobOtherSetting {
            get {
                return ((bool)(this["mobOtherSetting"]));
            }
            set {
                this["mobOtherSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool harvestingHideSetting {
            get {
                return ((bool)(this["harvestingHideSetting"]));
            }
            set {
                this["harvestingHideSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection membersSetting {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["membersSetting"]));
            }
            set {
                this["membersSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection typeMembersSetting {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["typeMembersSetting"]));
            }
            set {
                this["typeMembersSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection positionSetting {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["positionSetting"]));
            }
            set {
                this["positionSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool showExpSetting {
            get {
                return ((bool)(this["showExpSetting"]));
            }
            set {
                this["showExpSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string userSetting {
            get {
                return ((string)(this["userSetting"]));
            }
            set {
                this["userSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string passSetting {
            get {
                return ((string)(this["passSetting"]));
            }
            set {
                this["passSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool saveSetting {
            get {
                return ((bool)(this["saveSetting"]));
            }
            set {
                this["saveSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool avalonDronesSetting {
            get {
                return ((bool)(this["avalonDronesSetting"]));
            }
            set {
                this["avalonDronesSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool otherBossesSetting {
            get {
                return ((bool)(this["otherBossesSetting"]));
            }
            set {
                this["otherBossesSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool devModeSetting {
            get {
                return ((bool)(this["devModeSetting"]));
            }
            set {
                this["devModeSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool showPlayersSetting {
            get {
                return ((bool)(this["showPlayersSetting"]));
            }
            set {
                this["showPlayersSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool showPlayerSetting {
            get {
                return ((bool)(this["showPlayerSetting"]));
            }
            set {
                this["showPlayerSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string v4Setting {
            get {
                return ((string)(this["v4Setting"]));
            }
            set {
                this["v4Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool showOnTopSetting {
            get {
                return ((bool)(this["showOnTopSetting"]));
            }
            set {
                this["showOnTopSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int windowScaleSetting {
            get {
                return ((int)(this["windowScaleSetting"]));
            }
            set {
                this["windowScaleSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int windowSizeSetting {
            get {
                return ((int)(this["windowSizeSetting"]));
            }
            set {
                this["windowSizeSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool showGuildSetting {
            get {
                return ((bool)(this["showGuildSetting"]));
            }
            set {
                this["showGuildSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int itemsHeightSetting {
            get {
                return ((int)(this["itemsHeightSetting"]));
            }
            set {
                this["itemsHeightSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int itemsWidthSetting {
            get {
                return ((int)(this["itemsWidthSetting"]));
            }
            set {
                this["itemsWidthSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool showPlayerItemsDevModeSetting {
            get {
                return ((bool)(this["showPlayerItemsDevModeSetting"]));
            }
            set {
                this["showPlayerItemsDevModeSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool dragAndDropSetting {
            get {
                return ((bool)(this["dragAndDropSetting"]));
            }
            set {
                this["dragAndDropSetting"] = value;
            }
        }
    }
}
